# Numpy

## NumPy’s array class ndarray == array. Python array.array != ndarray

In [2]:
#import 
import numpy as np

arr = np.array([1.2,2,3,4,5], dtype = np.float64)
print(arr)
print(type(arr))

[1.2 2.  3.  4.  5. ]
<class 'numpy.ndarray'>


In [3]:
matrix = np.array([1,2,3,4,5,1,24,67,81,2,3, 23]).reshape(3,4)
print(matrix)
print(type(matrix))
print(matrix.T) # = matrix.reshape(4,3)

[[ 1  2  3  4]
 [ 5  1 24 67]
 [81  2  3 23]]
<class 'numpy.ndarray'>
[[ 1  5 81]
 [ 2  1  2]
 [ 3 24  3]
 [ 4 67 23]]


In [4]:
a = np.arange(10,100,5).reshape(3, 6)
print(a)

[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]


In [5]:
o = np.ones(5, dtype=np.int32)
print("ones", o)
z = np.zeros((2,5), dtype=np.float64)
print("zeros\n", z)
i = np.identity(6)
print('identity\n', i)

ones [1 1 1 1 1]
zeros
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
identity
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Basic operations

In [27]:
a = np.array([20, 30, 40, 50])

b = np.arange(4)

print('a - b',a - b)
print('b**2', b**2)
print('12 * np.cosin(a)',12 * np.cos(a))
print('a > 32', a > 32)


a - b [20 29 38 47]
b**2 [0 1 4 9]
12 * np.cosin(a) [ 4.89698474  1.8510174  -8.00325674 11.57959234]
a > 32 [False False  True  True]


In [7]:
matrix2 = np.random.rand(4,5)
print("matrix2\n", matrix2)
print('\nmatrix@matrix2 == matrix.dot(matrix2)\n',matrix@matrix2 == matrix.dot(matrix2))

matrix2
 [[0.37262126 0.01246788 0.80739491 0.92232398 0.44549125]
 [0.48949632 0.93919697 0.8346266  0.64487777 0.05289681]
 [0.83465044 0.52560696 0.3924288  0.42497259 0.25615507]
 [0.41973975 0.92341309 0.81762749 0.52302914 0.0394906 ]]

matrix@matrix2 == matrix.dot(matrix2)
 [[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


## Using numpy to explore dataset

In [8]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [9]:
print(type(iris))
print(type(iris.data),type(iris.target))

<class 'sklearn.utils._bunch.Bunch'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [10]:
print('shape: ', iris.data.shape)
print('size: ', iris.data.size)

shape:  (150, 4)
size:  600


In [11]:
iris.data.ndim

2

In [12]:
iris.data.dtype

dtype('float64')

In [13]:
print(iris.feature_names)
print(iris.data)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3

In [14]:
print(iris.target_names[0:])
print(iris.target[:51])

['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
